version: '3.9'

services:
  java_app:
    container_name: java_app
    image: sophia/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5433/java-docker
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=161201
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 161201
      POSTGRES_DB: java-docker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}